apiVersion: v1
kind: Service
metadata:
  name: my-scraper-service
spec:
  selector:
    app: my-scraper
  ports:
    - protocol: TCP
      port: 80        # Porta dentro do cluster (service)
      targetPort: 8080 # Porta do container
